### ISSUE TITLE
Should rust-uchardet depend on rust-encoding?

### ISSUE THREAD

**Issue by emk** [emk/rust-uchardet#1]
It looks like [`encoding`](https://github.com/lifthrasiir/rust-encoding) is rapidly becoming the encoding library of choice, and `uchardet` would be much more useful if it could actually transcode data directly. We have several choices:
1. Keep `uchardet` as a strictly low-level library, and create a new library which depends on both it and `encoding`.
2. Depend on `encoding`, and let the linker decide whether or not to pull in all of `encoding`.
3. Depend on `encoding`, and create a second internal library that provides the low-level API without pulling in everything.

I'm leaning towards (2), with the option of splitting out (3) at a latter date if somebody asks for it. But I'm open to suggestions.

**Comment by lifthrasiir** [comment]
lifthrasiir/rust-encoding#64 is a variation over (1). How do you think about that?

**Comment by sanmai-NL** [comment]
I'm pro solution 1. It shouldn't be too much work to split this crate; it lets consumers avoid downloading `encoding`; it reduces the LTO slowdown. This is what I presume. What is the status of this ticket? (Wondering since it's almost 3 years old and the only open one.)

**Comment by emk** [comment]
This ticket is on hold until somebody tells me, "Yes, there's a lightweight spinoff of `encoding` that contains just the encoding names and not a lot of extra data." This might already exist, for all I know!

**Comment by sanmai-NL** [comment]
Okay, seems like a different kind of issue than the one you proposed solving in the initial report? So ultimately the issue is, then, that `encoding` should be split up rather than this crate? Feel free to correct me, I'm trying to gain an understanding of how I could help.

**Comment by emk** [comment]
Yeah, I'd love for there to be a standard list of ISO encodings we could use, but which didn't require pulling in a big dependency.

Or we might limit ourselves to the [WhatWG encodings](https://encoding.spec.whatwg.org/), if there's some small, popular Rust crate we could use. This might actually require the maintainers of different encoding-related crates to sit down and decide on a plan.

**Comment by emk** [comment]
I'm deprecated `rust-uchardet` in favor of the Rust `chardet` crate, which is a port of basically the same code to native Rust. So this issue is now moot. Thank you!
