### ISSUE TITLE
No detection tests, test in `README` fails

### ISSUE THREAD

**Issue by sanmai-NL** [emk/rust-uchardet#8]
It seems the test in the [`README`](https://github.com/emk/rust-uchardet/blob/65b833e7be85f57d5fcef5913224812d9c33a4ee/README.md) fails on `rustc 1.20.0-nightly (afe145d22 2017-07-23)`.
This test and any such detection test isn't in the code base, as far as I could find.

```rust
extern crate uchardet;

use uchardet::detect_encoding_name;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn t1() {
        assert_eq!(
            "UTF-8",
            detect_encoding_name("français".as_bytes()).unwrap()
        );
    }
}
```

```
running 1 test
thread 'tests::t1' panicked at 'assertion failed: `(left == right)`
  left: `"UTF-8"`,
 right: `"IBM852"`', src/lib.rs:11:8
```

How to fix this case? Then, do you also wish for a test to be added? As unit or integration test? Some guidance would be welcome.

**Comment by emk** [comment]
So that particular test got removed almost everywhere, but was accidentally left in the `README.md`. Recent updates to upstream cause the library to be less reliable for single-word strings like `français`, and this test now fails. I have other detection tests, if I recall correctly, for slightly longer strings that will still be detected reliably.

Honestly, it was mostly luck that such a short test ever worked in any case.

**Comment by emk** [comment]
Here are [three detection tests](https://github.com/emk/rust-uchardet/blob/master/src/lib.rs#L79-L85), for example:

```rust
assert_eq!("ASCII",
           detect_encoding_name("ascii".as_bytes()).unwrap());
assert_eq!("UTF-8",
           detect_encoding_name("©français".as_bytes()).unwrap());
assert_eq!("WINDOWS-1252",
           detect_encoding_name(&[0x46, 0x93, 0x72, 0x61, 0x6e, 0xe7, 0x6f,
```

Since we do have three detection tests in the source code, I believe the only the only thing we need to do here is remove the broken test from the `README.md` file.

**Comment by emk** [comment]
The README.md is fixed.

By the way, nearly all the tests for this library are in the doc comments. These are checked automatically when `cargo test` is run.

**Comment by sanmai-NL** [comment]
Note, I searched for `test`, which seems to reveal unit tests and integration tests but not doctests. I've never used the latter so far.
